### ISSUE TITLE
To-do before paper submission

### ISSUE THREAD

**Issue by halexand** [AlexanderLabWHOI/EUKulele#3]
- [x] Add license.
- [ ] Codify flow diagram. 
- [x] Add BUSCO assessment for metaT and metaG
- [x] Move away from `config.yaml` and towards commandline input. One issue I see here is how to deal with the cluster config file. I feel that it is easiest just to keep it as is. How to we use `submit-script.sh` with commandline ops?

**Comment by akrinos** [comment]
[Remodeling branch](https://github.com/AlexanderLabWHOI/EUKulele/tree/remodeling) now has a fully Python-based option, in which there is a file, `EUKulele-config.py`, that will parse the command-line flags from the `config.yaml` file if you wish. Otherwise, everything can be specified as flags. This also resolves the issues with the `cluster.yaml` file, because the SLURM options only need to be specified once for the entire run.

**Comment by akrinos** [comment]
[Akrinos branch](https://github.com/AlexanderLabWHOI/EUKulele/tree/akrinos) demonstrates the BUSCO assessment workflow for one sample organism for the METs. I need to think more about how to do it for the MAGs, because it will require more design on my part. Currently, I am using my outputs from taxonomy estimation and visualization for the BUSCO process. In the new workflow in the remodeling branch, users may specify as many organisms/classes/etc. as they wish in either a provided file, a space-separated list as command-line inputs, or a tab-delimited file (need the names of the organisms at whatever taxonomic level you're interested in, then what that taxonomic level is).
